// zer0fucks compiler, written by zer0sh0t
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv)
{
    if (argc == 1)
    {
        printf("please pass the input brainfuck file and output c file names!");
        return -1;
    }

    char bf_ch, *out_name, compile_cmd[100]="gcc ";
    int hm_whiles = 0;
    FILE *in_ptr, *out_ptr;
    in_ptr = fopen(argv[1], "r");
    if (argc == 2)
    {
        out_name = "temp.c";
    }
    else
    {
        out_name = argv[2];
    }
    out_ptr = fopen(out_name, "w");

    fprintf(out_ptr, "// generated by zer0fucks compiler\n#include <stdio.h>\n\nint main()\n{\n");
    fprintf(out_ptr, "\tchar mem_block[30000], *ptr = mem_block;\n"); // brainfuck provides only 3 kb of memory
    if (in_ptr == NULL)
    {
        printf("brainfuck file can't be opened\n");
    }
    else
    {
        do
        {
            bf_ch = fgetc(in_ptr);
            char output[50] = "\t";
            for (int i = 0; i < hm_whiles; i++)
            {
                strcat(output, "\t");
            }

            if (bf_ch == '>')
            {
                strcat(output, "ptr++;\n");
                fprintf(out_ptr, output);
            }
            else if (bf_ch == '<')
            {
                strcat(output, "ptr--;\n");
                fprintf(out_ptr, output);
            }
            else if (bf_ch == '+')
            {
                strcat(output, "++(*ptr);\n");
                fprintf(out_ptr, output);
            }
            else if (bf_ch == '-')
            {
                strcat(output, "--(*ptr);\n");
                fprintf(out_ptr, output);
            }
            else if (bf_ch == '[')
            {
                char tabs[20];
                strcpy(tabs, output);
                strcat(output, "while(*ptr)\n");
                strcat(output, tabs);
                strcat(output, "{\n");
                fprintf(out_ptr, output);
                ++hm_whiles;
            }
            else if (bf_ch == ']')
            {
                output[strlen(output)-1] = '\0';
                strcat(output, "}\n");
                fprintf(out_ptr, output);
                --hm_whiles;
            }
            else if (bf_ch == '.')
            {
                strcat(output, "putchar(*ptr);\n");
                fprintf(out_ptr, output);
            }
            else if (bf_ch == ',')
            {
                strcat(output, "*ptr=getchar();\n");
                fprintf(out_ptr, output);
            }
        } while (bf_ch != EOF);
    }
    fprintf(out_ptr, "\treturn 0;\n}");
    fclose(in_ptr);
    fclose(out_ptr);

    strcat(compile_cmd, out_name);
    strcat(compile_cmd, " -o temp.out");
    system(compile_cmd);
    system("temp.out");
    if (argc == 2)
    {
        system("rm temp.c");
    }
    system("rm temp.out");

    return 0;
}
